# Generated by Django 3.2.18 on 2023-03-24 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='company_name',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Название компании'),
        ),
    ]
