# Generated by Django 3.2.18 on 2023-03-27 10:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_company_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='slug',
            field=models.SlugField(blank=True, max_length=150, null=True, verbose_name='Слаг компании'),
        ),
    ]
