# Generated by Django 3.2.18 on 2023-03-27 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_user_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='slug',
            new_name='company_slug',
        ),
        migrations.AddField(
            model_name='user',
            name='company_number_slug',
            field=models.SlugField(blank=True, max_length=8, null=True, unique=True, verbose_name='Уникальный номер заказа'),
        ),
    ]
