# Generated by Django 3.2.18 on 2023-03-24 17:10

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields
import smart_selects.db_fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Area',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название района')),
            ],
            options={
                'verbose_name': 'Район',
                'verbose_name_plural': 'Районы',
            },
        ),
        migrations.CreateModel(
            name='City',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название города')),
                ('area', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citys', to='zakaz.area', verbose_name='Район')),
            ],
            options={
                'verbose_name': 'Город',
                'verbose_name_plural': 'Города',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=8, unique=True, verbose_name='Уникальный номер заказа')),
                ('name', models.CharField(max_length=100, verbose_name='Имя заказчика')),
                ('surname', models.CharField(max_length=250, verbose_name='Фамилия заказчика')),
                ('father_name', models.CharField(blank=True, max_length=250, null=True, verbose_name='Отчество заказчика')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Номер телефона')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Электронная почта заказчика')),
                ('cadastral_number', models.CharField(max_length=50, verbose_name='Кадастровый номер')),
                ('street', models.CharField(max_length=250, verbose_name='Улица')),
                ('house_number', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Номер дома')),
                ('building', models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Строение/Корпус')),
                ('square', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Площадь участка')),
                ('square_unit', models.CharField(choices=[('sq_m', 'м²'), ('hectometer', 'га')], max_length=10, verbose_name='Еденица площади')),
                ('length', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Длина')),
                ('length_unit', models.CharField(choices=[('m', 'м'), ('кь', 'км')], max_length=10, verbose_name='Еденица длины')),
                ('width', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Ширина')),
                ('width_unit', models.CharField(choices=[('m', 'м'), ('кь', 'км')], max_length=10, verbose_name='Еденица ширины')),
                ('height', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='Высота')),
                ('height_unit', models.CharField(choices=[('m', 'м'), ('floor', 'этаж')], max_length=10, verbose_name='Еденица высота')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('date', models.DateTimeField(auto_now_add=True, verbose_name='Дата заявки')),
                ('user_purpose_building', models.CharField(max_length=200, verbose_name='Пользовательское назначение здания')),
                ('area', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='region', chained_model_field='region', on_delete=django.db.models.deletion.CASCADE, to='zakaz.area')),
                ('city', smart_selects.db_fields.ChainedForeignKey(auto_choose=True, chained_field='area', chained_model_field='area', on_delete=django.db.models.deletion.CASCADE, to='zakaz.city')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='PurposeBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=150, verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Назначение здания',
                'verbose_name_plural': 'Назначения зданий',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=180, verbose_name='Название региона')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='TypeWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=50, verbose_name='Тип работы')),
            ],
            options={
                'verbose_name': 'Тип работы',
                'verbose_name_plural': 'Типы работ',
            },
        ),
        migrations.CreateModel(
            name='WorkObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=150, verbose_name='Цель работы')),
            ],
            options={
                'verbose_name': 'Цель работы',
                'verbose_name_plural': 'Цели работ',
            },
        ),
        migrations.CreateModel(
            name='OrderFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='', verbose_name='Файл')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='zakaz.order', verbose_name='Заказы')),
            ],
            options={
                'verbose_name': 'Файлы к заказу',
                'verbose_name_plural': 'Файлы к заказам',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='purpose_building',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='zakaz.purposebuilding', verbose_name='Назначение здания'),
        ),
        migrations.AddField(
            model_name='order',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='zakaz.region', verbose_name='Регион'),
        ),
        migrations.AddField(
            model_name='order',
            name='type_work',
            field=models.ManyToManyField(related_name='orders', to='zakaz.TypeWork', verbose_name='Виды работ'),
        ),
        migrations.AddField(
            model_name='order',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AddField(
            model_name='order',
            name='work_objective',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='zakaz.workobjective', verbose_name='Цель работы'),
        ),
        migrations.AddField(
            model_name='area',
            name='region',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='areas', to='zakaz.region', verbose_name='Регион'),
        ),
    ]
