# Generated by Django 3.2.18 on 2023-03-22 11:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PurposeBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(max_length=150, verbose_name='Назначение')),
            ],
            options={
                'verbose_name': 'Назначение здания',
                'verbose_name_plural': 'Назначения зданий',
            },
        ),
        migrations.CreateModel(
            name='WorkObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objective', models.CharField(max_length=150, verbose_name='Цель работы')),
            ],
            options={
                'verbose_name': 'Цель работы',
                'verbose_name_plural': 'Цели работ',
            },
        ),
        migrations.RenameField(
            model_name='order',
            old_name='title',
            new_name='comment',
        ),
        migrations.AddField(
            model_name='order',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Дата заявки'),
        ),
        migrations.AddField(
            model_name='order',
            name='purpose_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='zakaz.purposebuilding', verbose_name='Назначение здания'),
        ),
        migrations.AddField(
            model_name='order',
            name='work_objective',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='zakaz.workobjective', verbose_name='Цель раоты'),
        ),
    ]
