# Generated by Django 3.2.18 on 2023-03-24 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='purpose_building',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='orders', to='zakaz.purposebuilding', verbose_name='Назначение здания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='user_purpose_building',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Пользовательское назначение здания'),
        ),
    ]
