# Generated by Django 3.2.18 on 2023-03-23 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0002_auto_20230322_1155'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='user_purpose_building',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Пользовательское назначение здания'),
        ),
        migrations.AlterField(
            model_name='order',
            name='type_work',
            field=models.ManyToManyField(related_name='orders', to='zakaz.TypeWork', verbose_name='Виды работ'),
        ),
    ]
