# Generated by Django 3.2.18 on 2023-03-25 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0002_auto_20230324_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='height',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Высота'),
        ),
        migrations.AlterField(
            model_name='order',
            name='length',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Длина'),
        ),
        migrations.AlterField(
            model_name='order',
            name='square',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Площадь участка'),
        ),
        migrations.AlterField(
            model_name='order',
            name='width',
            field=models.DecimalField(decimal_places=3, max_digits=8, verbose_name='Ширина'),
        ),
    ]
