# Generated by Django 3.2.18 on 2023-03-24 08:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0003_auto_20230323_1535'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='building',
            field=models.PositiveBigIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Строение/Корпус'),
        ),
        migrations.AlterField(
            model_name='order',
            name='height_unit',
            field=models.CharField(blank=True, choices=[('m', 'м'), ('floor', 'этаж')], max_length=10, null=True, verbose_name='Еденица высота'),
        ),
        migrations.AlterField(
            model_name='order',
            name='length_unit',
            field=models.CharField(blank=True, choices=[('m', 'м'), ('кь', 'км')], max_length=10, null=True, verbose_name='Еденица длины'),
        ),
        migrations.AlterField(
            model_name='order',
            name='square_unit',
            field=models.CharField(blank=True, choices=[('sq_m', 'м²'), ('hectometer', 'Га')], max_length=10, null=True, verbose_name='Еденица площади'),
        ),
        migrations.AlterField(
            model_name='order',
            name='width_unit',
            field=models.CharField(blank=True, choices=[('m', 'м'), ('кь', 'км')], max_length=10, null=True, verbose_name='Еденица ширины'),
        ),
    ]
