# Generated by Django 3.2.18 on 2023-03-28 06:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0005_remove_order_company_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='number_slug',
        ),
    ]
