# Generated by Django 3.2.18 on 2023-03-28 09:31

from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0006_remove_order_number_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, verbose_name='Название ведомства')),
                ('director_position', models.CharField(max_length=150, verbose_name='Должность руководителя ведомства')),
                ('director_name', models.CharField(max_length=20, verbose_name='Имя руководителя')),
                ('director_surname', models.CharField(max_length=50, verbose_name='Фамилия руководителя')),
                ('director_patronymic', models.CharField(max_length=30, verbose_name='Отчество руководителя')),
                ('phone_number', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None, verbose_name='Телефон ведомства')),
                ('email', models.EmailField(max_length=254, verbose_name='Электронная почта ведомства')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='region_department', to='zakaz.region', verbose_name='Регион ведомства')),
            ],
            options={
                'verbose_name': 'Ведомство',
                'verbose_name_plural': 'Ведомства',
            },
        ),
    ]
