# Generated by Django 3.2.18 on 2023-03-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0006_remove_order_number_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='region',
            name='cadastral_region_number',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Кадастровый номер'),
        ),
    ]
