# Generated by Django 3.2.18 on 2023-03-29 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0007_department'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='object_name',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название объекта'),
        ),
    ]
