# Generated by Django 3.2.18 on 2023-03-28 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0007_region_cadastral_region_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='area',
            name='cadastral_region_number',
            field=models.CharField(blank=True, max_length=2, null=True, verbose_name='Кадастровый номер'),
        ),
    ]
