# Generated by Django 3.2.18 on 2023-03-31 08:38

from django.db import migrations
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0014_auto_20230329_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='map',
            field=tinymce.models.HTMLField(blank=True, null=True, verbose_name='Карта участка'),
        ),
    ]
