# Generated by Django 3.2.18 on 2023-03-30 12:40

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0014_auto_20230329_1148'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='coordinates',
            field=django.contrib.postgres.fields.ArrayField(base_field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Координаты'), size=None), default=[], size=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='map',
            field=models.CharField(blank=True, max_length=5000, null=True, verbose_name='Карта'),
        ),
    ]
