# Generated by Django 3.2.18 on 2023-03-31 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0015_order_map'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='map',
            field=models.TextField(blank=True, null=True, verbose_name='Карта участка'),
        ),
    ]
