# Generated by Django 3.2.18 on 2023-04-06 09:49

from django.db import migrations, models
import zakaz.models


class Migration(migrations.Migration):

    dependencies = [
        ('zakaz', '0018_auto_20230405_0813'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='map',
            field=models.ImageField(blank=True, null=True, upload_to=zakaz.models.get_image_path),
        ),
    ]
